name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' 

      # Instalar dependencias con una variable que fuerza la descarga de Cypress
      - name: Install Dependencies
        run: npm install
        working-directory: ./tesis
        env:
          # Esta variable fuerza a Cypress a reinstalar el binario en caso de problemas
          CYPRESS_INSTALL_BINARY: 1 
          
      # El paso 4 (Download Cypress Binary) NO es necesario si usamos CYPRESS_INSTALL_BINARY

      # El paso 5 (Fix Cypress Permissions) lo quitamos para evitar conflictos
      
      # 6. Ejecutar pruebas
      - name: Run Tests
        # Usamos 'npx' para asegurar que el binario local de cypress se ejecute correctamente
        run: npx npm test
        working-directory: ./tesis